### ISSUE TITLE
Output if `--check` and `--quiet` are used

### ISSUE THREAD

**Issue by ikatanic** [ambv/black#139]
Do I understand correctly that `--check` flag is basically a linter mode?

When I'm using it that way I don't want it to print 100 lines about already well formatted files, so naturally I use `--quiet` as well. But that also suppresses lines about not well formatted files, so even though exit code is non-zero there is nothing on stdout or stderr, which is not helpful.

What do you think about it?

**Comment by ambv** [comment]
Well, if you run check on a directory, it will output you one line per every file it checked. If you're only interested in the changed ones, you can filter out the unchanged ones with `grep -v "good job"`.

I understand where you're coming from but I don't want to change this because another person will come asking to have the current behavior back :-) Unix philosophy: tools should be simple and consistent so that they can be composed with other tools.
