### ISSUE TITLE
Atom/Nuclide integration

### ISSUE THREAD

**Issue by mojodna** [ambv/black#176]
The README mentions that you're working on Atom/Nuclide integration. I'm looking forward to such a thing but would like to be able to asynchronously track progress/availability. If this works for you, this issue can remain open (and interested parties can subscribe) until there's progress (and you'll have a set of interested parties to beta test / contribute).

Thoughts?

**Comment by ambv** [comment]
Good idea.

### Plans
1. Make Black an option in Palantir's Language Server so that people can use it if they have plugins revolving around that.
2. Make Black an explicit option in Nuclide (vs. the current implicit YAPF).

### Workaround for now
For the time being, consider using Atom's [on-save](https://atom.io/packages/on-save) plugin.

**Comment by rupert** [comment]
@mojodna I recently wrote [pyls-black](https://github.com/rupert/pyls-black) which is a Black plugin for the [Python Language Server](https://github.com/palantir/python-language-server). You can use it in Atom, and presumably Nuclide, by installing `atom-ide-ui` and `ide-python`. Hope you find it useful.

**Comment by rupert** [comment]
See also the [Python Language Server](https://github.com/ambv/black#python-language-server) section in the `README` - perhaps the bit below that (_Atom/Nuclide integration is planned by the author_) could be updated to reference this too?

**Comment by JelleZijlstra** [comment]
As of #456 we now link to an Atom plugin for Black (thanks @hauntsaninja).
