### ISSUE TITLE
Feature-Request: rigorous tab-to-4 conversion/fix option?

### ISSUE THREAD

**Issue by geeohgeegeeoh** [ambv/black#265]
I looked,  but couldn't see logic which could fix tabs to 4 spaces, and uplift mixed tab/space code to be 4 space only. Is it possible that given you have a strong model of code indent, you could detect and fix erroneous tab instances?

**Comment by ambv** [comment]
Do you have an example where Black doesn't currently do a good job at this?

You need to understand that in the presence of mixed tabs and spaces Python 2 assumed tabs as having 8 spaces. I can't do anything else here because it would be invalid.

If you only used tabs, they are treated as a single indent event, so they are translated to 4 spaces transparently.

**Comment by geeohgeegeeoh** [comment]
ok. PBCK. The "tabs" it preserved were inside """ .... """ comment strings.
I see all my code tabs being replaced.

close, as EFOOLISHUSER.

-G

**Comment by jaraco** [comment]
This issue is still an issue for me. I've attempted to run black on my projects with tabs, but when I do, all of the docstrings remain indented with tabs, causing linters to fail. It would really be nice if there were an option to include docstrings when converting from tabs to spaces. This one issue has prevented me from adopting black in the projects I maintain.

**Comment by jaraco** [comment]
This issue continues to cause me grief. I find I have to use my editor to convert `^\t\t\t` to `            ` and similarly for indent levels 2 and 1, after running black. At least for docstrings, I really wish black would convert the indentation.
