### ISSUE TITLE
Give same returncode for standard behaviour and --check

### ISSUE THREAD

**Issue by jgirardet** [ambv/black#285]
Hello,
i'ts about plugin developement for black.
With the standard behaviour you have the same returncode for formatted or already formatted.
If nothing changed, you don't want to apply the new black "out" to the current file because there are supposed to be the same and the editor could believe (and sublimetext does) something changed.

The only way to differenciate it is to "parse" the err output looking for "already well formatted, good job".
It's a bit awfull and this message could change in future release.

The other way to do it is run black twice, first with --check and then standard way. but ...

So at the end it would be more consitent to have same code for --check and standard behaviour.

Jimmy

**Comment by ambv** [comment]
This needs to stay separate. Originally I had that behavior and some integrations were very hard to do since some plugin systems popular with some editors (I recall Vim and PyCharm) treat non-zero return codes as tool failure.

Essentially, there isn't a single standard and everything is terrible.

What your plugin could be doing instead, is use --diff and apply it to the editor output. This is what VSCode is doing for example and I believe this is the best behavior.

**Comment by jgirardet** [comment]
I do not see usage of --diff in VScode.
It seems to be very clear for you but applying a diff to a python string/file/stream is not something very clear for myself. I see nothing in the standard library to do it

**Comment by zsol** [comment]
You can pipe the output of `black --diff` to anything that understands the [unified diff format](https://en.wikipedia.org/wiki/Diff#Unified_format), for example the `patch` command on unix systems. You could check if the output of `black --diff` is empty to know if there are any changes to be made. If it's not empty, you can pass it unmodified to `patch -p0`

**Comment by jgirardet** [comment]
I think path does not work on windows.
and this way is very  very verbose.  It makes run a second shell command whereas the following is so simple.
```
if "already well formatted, good job" in error_message:
      # just exit with status message
      sublime.status_message("Sublack: %s" % error_message)
 else:
     # update the current file with black output
     self.view.replace(edit, all_file, out
```

Anyway thanks for your answers guys.
 I will have to closely look for any change change in black stderr :-).

By the way why not only change the first characer in stderr. Actually it's "-" for change or no change. Because we can't have different status code, maybe could we have stderr first character changing.
Far example : "- already formatted" an "~ reformatted".
So You can later changer text message without anyone care.

**Comment by ambv** [comment]
@jgirardet: note, too see "already well formatted", this will require `--verbose` with Black 18.6b0. You'll have to pin the minimal supported version in the next version of sublack.

I needed to add `--verbose` because we want to also report on paths ignored via `--exclude=` so that users can debug issues with Black ignoring their files.

**Comment by jgirardet** [comment]
thanks keeping me in touch

**Comment by jgirardet** [comment]
do you think, in stdin/stdout mode that stderr will stay empty (not in verbose mode) when nothing changes (I mean in future releases).
Because that solves the problem

**Comment by ambv** [comment]
@jgirardet, oh, good point!

In default level of output (no --verbose and no --quiet) I will now always emit the summary. Before 18.6b0 I would only emit the summary if more than one file was given which made sense at the time since there was *always* a line about the file passed to the formatter. Now if the file isn't changed, there would be no output, which might confuse the user, so I made it more consistent. The following will always appear, regardless of how many files you're passing:
```
All done! ✨ 🍰 ✨
1 file left unchanged.
```

**Comment by Fernal73** [comment]
What about pre-commit hooks from pre-commit? Any way of modifying the default behaviour?

**Comment by Fernal73** [comment]
> What about pre-commit hooks from pre-commit? Any way of modifying the default behaviour?

There's a workaround for this here:

https://stackoverflow.com/questions/58398995/black-as-pre-commit-hook-always-fails-my-commits

I'd rather black allow a command line option to reconfigure the return code if needed.
