### ISSUE TITLE
Does not comply with E203 from pep8

### ISSUE THREAD

**Issue by horta** [ambv/black#315]
Operating system:
Python version: 3.6
*Black* version: 18.6b1
Does also happen on master: yes

Create a file with

`tup = nsamples, nalleless[i : i + size], i, size`

and black won't correct the white spaces around `:`.

**Comment by JelleZijlstra** [comment]
pep8 is wrong here. Quoting black's README: "This behaviour may raise E203 whitespace before ':' warnings in style guide enforcement tools like Flake8. Since E203 is not PEP 8 compliant, you should tell Flake8 to ignore these warnings."

In general when using black it's safe to disable formatting-related errors in tools like flake8; black takes care of the styling minutiae for you.

**Comment by horta** [comment]
Thanks a lot, @JelleZijlstra !

**Comment by svenevs** [comment]
This issue comes up high in the search results, dropping some additional links for those who land here:

- https://github.com/psf/black/blob/main/docs/guides/using_black_with_other_tools.md with hints for other tools and a thorough list of examples of how to control things using the various configuration files available (sweet!).
- For `flake8` specifically, you want `--extend-ignore=E203` not `--ignore=203` as explained by the [flake8 maintainer](https://stackoverflow.com/a/68172142)
