### ISSUE TITLE
PyDev integration

### ISSUE THREAD

**Issue by agb80** [ambv/black#331]
Does anyone knows if there is a way to integrate black with Eclipse PyDev plugin?

**Comment by ambv** [comment]
There is no integration now. I'd be open to somebody creating one and letting us know about it.

**Comment by rupert** [comment]
@agb80 it should be possible using:

* [Eclipse LSP4E](https://projects.eclipse.org/projects/technology.lsp4e)
* [Python Language Server](https://github.com/palantir/python-language-server)
* [pyls-black](https://github.com/rupert/pyls-black)

Python Language Server also supports a number of other linters and formatters (e.g. `isort`) that you might be interested in.

**Comment by agb80** [comment]
Interesting, will going to try it.
Thanks for let me know!!

**Comment by agb80** [comment]
Just for the record, the PyDev version 7.0.3 released at 2018-11-08 includes black support by default You can look at the details [here](https://www.pydev.org/history_pydev.html).

Thanks for your answers

**Comment by Stelminator** [comment]
For those wanting to use this on Python2 projects, I found that if I made a symbolic link to the black executable in the /bin directory of my python2 virtualenv, it started working.  I don't like to install things to the system python, so, `black` isn't on my `PATH`; not sure if relevant.  Leaving this here because I couldn't find an easy answer to this configuration elsewhere.
