### ISSUE TITLE
Configurable Indent Levels?

### ISSUE THREAD

**Issue by kwlzn** [ambv/black#378]
before lobbing a PR over, I wanted to spin up a quick discussion around adding an option to `black` to permit smoother interop with 2-space indent code bases.

At Twitter, we would like to experiment with adopting `black` as autofmt tooling in a few of our open source projects and potentially more widely across our internal monorepo. Our python code style is currently defined as such:

```
Python code style at Twitter closely follows PEP-8 and PEP-257 with the following modifications:

- Indent using two spaces (instead of four).
- Break lines at 100 characters or less.
```

we have on the order of many millions of lines of code that currently adopt this style and generally feel like it's a net improvement over 4 space indent (nested blocks can fit more code per line, etc etc). [pants](https://github.com/pantsbuild/pants) and [pex](https://github.com/pantsbuild/pex) are good concrete examples of projects that started at Twitter and were later open sourced with a continuation of this python code style.

I realize `black` is intended to be opinionated and have little to no config - but to me, line length and indent level both seem like a fairly fundamental configurable for most shops, so I'd put this in a very similar category as the existing `--line-length` option:

```
-l, --line-length INTEGER   Where to wrap around.  [default: 88]
```

with that said, how would folks feel about adding a new `--indent-level={2|4}` flag to `black` to permit easier interop for code bases that take this fundamental stance? I would be happy to cut a PR that implements this as long as there's consensus that this would be reasonable.

**Comment by ambv** [comment]
Please consider dropping two-space indents. Black will not support this style.

**Comment by kwlzn** [comment]
k, thanks.

**Comment by ambv** [comment]
Thanks for your detailed comment. Note you are commenting on a closed issue. Your attempt to use `--line-length=` as a precedent for allowing two-space indents is understandable but I disagree with it.

Line length controls what happens on the *right* of the line, whereas a different indentation level would change what happens on the *left* of the line. The former affects *some* lines whereas the latter would affect *all* lines.

Two space indents are not distinct enough to be recommended by the Black coding style.

**Comment by pausan** [comment]
True. I'm also aware the issue is closed, but I wanted to make my point to see if it could be reopened and reconsidered. It won't make sense to open a new issue if the topic is going to be the same as this one.

Just for a final argument, consider the choice of 88 characters by default. It is an interesting choice made because:
"This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library)."

Shorter files in number of lines... I'm sure indentation level of 2 also produces shorter files.

I mean, we come back to styling choices which are subjective. If you prefer 4-space indented files and you don't want to provide an option in black for 2 spaces, it is your project and your choice, I just though it would be an interesting addition that could potentially benefit the project, spreaden its adoption and still preserve its essence & formatting rules. There is nothing else I can say. Totally your choice.

I hope you can re-reconsider, but otherwise thanks for your time reading and answering these thoughts! The project is still really cool.

**Comment by pausan** [comment]
For the record, in case @kwlzn or anybody else stumbles with black and wants 2 spaces instead of 4 spaces: 

    $ pip3 install cblack

I've created a public repository for a customized black [cblack](https://github.com/pausan/cblack) in github and a build has been deployed to [PIP package](https://pypi.org/project/cblack/) to make it easier to use.

I decided to create a wrapper project instead of using the hack I was using of patching black.py since I want to use it inside of my organization. Indentation is forced to 2 spaces in cblack, since whoever wants 4 spaces can use black directly.

Last thing I want to say is that black is awesome, othwerise I wouldn't be wrapping it for my particular needs. Thanks!

**Comment by desbma** [comment]
For those of you who want to try `black`, but only want 2 spaces indentation, I have made a fork: https://github.com/desbma/black-2spaces

Test are obviously broken, and I don't know if I intend to maintain it, but this is currently [a one line change](https://github.com/desbma/black-2spaces/commit/e9de72c180edf74d7372609c93179954bdd79f11), and enough to test it.

**Comment by thalessa** [comment]
> For those of you who want to try `black`, but only want 2 spaces indentation, I have made a fork: https://github.com/desbma/black-2spaces

Why can both 2 and 4 space supporters not just agree to compromise on 3?
