### ISSUE TITLE
Black mangles multiple assignments unnecessarily by introducing parentheses

### ISSUE THREAD

**Issue by crd** [ambv/black#434]
Operating system: macOS High Sierra 10.13.5 
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: Yes

Before `black`:

```python
xxx_pattern_with_no_padding = yyy_pattern_with_no_padding = zzz_pattern_with_no_padding = aaa_pattern_with_no_padding = r"\d{9}"

xxx = yyy = zzz = aaa = r"\d{9}"
```

After `black`:

```python
xxx_pattern_with_no_padding = (
    yyy_pattern_with_no_padding
) = zzz_pattern_with_no_padding = aaa_pattern_with_no_padding = r"\d{9}"

xxx = yyy = zzz = aaa = r"\d{9}"
```

Not sure why black is introducing those parentheses for the first line.

**Comment by zsol** [comment]
Agreed this is weird, maybe we should look at how to do this better

**Comment by ambv** [comment]
@crd, it's introducing them because your first line is too long and it tries to reflow it to fit 88 characters and this is one way to do it.

I don't think there's a better way to format this. If you'd like to keep your current formatting, use `# fmt: off` and `# fmt: on` between this block of code. If you'd like to improve your formatting, make single assingments per line, you'll use more lines but arguably it will be easier for your readers to figure out what's going on.

**Comment by akhmerov** [comment]
There are two aspects of the discussion here:

#### 1. Whether there is a reasonable real life scenario when chain assignments are more readable than alternatives.

Here @ambv suggested multiple single assignments as an alternative, and I don't think this is as clear.

A chain assignment is a good way to indicate that a bunch of variables are equal—otherwise the reader must compare the right hand sides.

In [my use case](https://gitlab.kwant-project.org/kwant/kwant/blob/master/kwant/builder.py#L1787-1798) (#919), we're providing the same implementation of a bunch of methods that raise the same error (the users confuse two classes in the codebase).

Here's a comparison of two approaches:

Multiple assignments:
```python
    hamiltonian = _require_system
    hamiltonian_submatrix = _require_system
    modes = _require_system
    selfenergy = _require_system
    inter_cell_hopping = _require_system
    cell_hamiltonian = _require_system
    precalculated = _require_system
```

Chain assignment:
```python
    hamiltonian = hamiltonian_submatrix = modes = selfenergy = \
    inter_cell_hopping = cell_hamiltonian = precalculated = \
        _require_system
```

It's not an obvious choice: multiple assignments have more redundancy and take longer to read, while in a chain assignment the follow-up lines aren't clearly related to the previous one. I'd still say that a chain assignment is slightly better.

#### 2. What is the most readable formatting of chain assignments.

This isn't contingent on the other question: even if a chain assignment is an inferior choice, black still *may* do a good job formatting it, and therefore if we agree that the current formatting is bad, it might still be worth to reopen the issue.

Wouldn't a line continuation be more readable than what black does right now?

I agree that parentheses are a better way of making split lines parse correctly, but this is not a fundamental advantage. The parentheses are only easier to understand because they introduce extra semantics and mean that "a whole bunch of things that follow are related".

In the chain assignments case this isn't true; the parentheses don't add any helpful semantics and are just distracting IMO.
