### ISSUE TITLE
Condense Multi-line Lists Where Possible?

### ISSUE THREAD

**Issue by rmorshea** [ambv/black#440]
Operating system: Ubuntu 18.04 LTS
Python version: 3.6.3
*Black* version: `master`

Currently I'm getting push back from a colleague about using `black` because it formats a long list like this:

```python
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 , 18, 19, 20, 21, 22, 23, 24, 25]

# or

l = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
    12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25,
]
```

Into an unreasonably long multi line expressions.

```python
l = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
]
```

Is this behavior intentional?

> It should be mentioned that this is an entirely hypothetical problem as I'm not sure I've ever needed a list like this.

**Comment by ljvmiranda921** [comment]
This has also been my problem. In our case, we need to create a predefined n-dimensional numpy array for one of our test cases, and `black` formats it similarly as above. Not sure if this is OK because it creates a very high LOC and personally doesn't look nice.

Maybe this can be resolved by putting the predefined arrays into an external file? I'm considering this as another option though.

**Comment by svanburen** [comment]
You could use a `# fmt: off` followed by `# fmt: on` block around those predefined arrays (discussed towards the top of this section https://github.com/ambv/black#the-black-code-style)

**Comment by rmorshea** [comment]
@svanburen I think the `fmt: off` and `fmt: on` solve this issue.
