### ISSUE TITLE
Consider switching line-length default to 79 chars, per PEP8

### ISSUE THREAD

**Issue by nottrobin** [ambv/black#498]
I've read [the justification](https://github.com/ambv/black#line-length) for using 88 chars as the default max-line-length in Black:

> This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, [90-ish seems like the wise choice](https://youtu.be/wf-BqAjZb8M?t=260). If you're paid by the line of code you write, you can pass --line-length with a lower number.

I'd like to suggest that this argument isn't strong enough to justify deviating from a strong standard that exists in the Python community and beyond. Not only does PEP8, and therefore Flake8 and almost every existing Python project use 79 chars, but this is also the default in [Prettier](https://prettier.io/docs/en/options.html) and is [the basis for the 72-character limit in Git commits](https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c). (And, conversely to the sarcastic addendum above - who cares if a file is a few lines longer in this day and age?)

I [proposed to Canonical's webteam](https://github.com/canonical-webteam/practices/issues/73#issuecomment-418130616) that we follow Black's standard of 88 chars, but our developers rejected the suggestion primarily based on that it's harder to view in their terminals - which is the reason for the 79 char limit in the first place. And so that we don't need to reconfigure all our Flake8-based CI for our projects immediately to be able to start using Black.

Since Black is meant to use sensible defaults and in most cases remain unconfigured, it seems a real shame that it deviates from PEP8 in just this one case, which will almost inevitably lead to a good number of projects that use it having just one config override for `--line-length=79` (as we're planning to do).

This is, of course, just my (or rather, our) 2 cents. Please feel free to make whatever choice you feel is right for the project.

**Comment by nkantar** [comment]
I agree with the @nottrobin.

I'm only using Black on some personal projects, and am using the default line length since I'm not _that_ opinionated. However, I would _prefer_ it to default to a 79-char limit, as that's the standard in much of the Python world, including the standard library itself.

That said, I can see the argument for bucking the trend—after all, should we blindly stick to tradition forever? It just seems that most Python code I encounter is either limited to 79 characters per line or not formatted at all (and not for reasons Black addresses anyway).

Either way, thank you for Black. It solved my personal [YAPF](https://github.com/google/yapf) config dilemmas once and for all (for now). 🎉

PS.: You might find [White](https://github.com/kennethreitz/white) amusing.

**Comment by zsol** [comment]
Sorry, this is unlikely to happen for the reasons you also found in the readme.

**Comment by nkantar** [comment]
@zsol No worries. Thanks for your contributions! 🖤

**Comment by Abdur-rahmaanJ** [comment]
This still bugs me. Preferring personal opinion over community standard
