### ISSUE TITLE
Suggestion: Add indenting to nested list comprehension inside dict comprehension to match dict formatting

### ISSUE THREAD

**Issue by ashleybartlett** [ambv/black#506]
Operating system: MacOS 10.14 (beta)
Python version: 3.7
*Black* version: 18.6b4
Does also happen on master: [Yes](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ALRANRdAD2IimZxl1N_Wk6rkWsZudzSMT2xmAtX-7MN3hbliw1OA31BdFn0Z9VyvCaR7fku_9AQcqKsn_8a21_qoOZpDfFV7DSY0QhPx74QZCoa9GkdLDiGW1xH5UDBGP4CZuACPLaMkA4lDOsGYWIHQo61gjQwYR7D_DhLTuPKd7OD2chUC4QEaYCalU8AhkwnuqOLqy6kTKjlMsfsxys3bH4VjbA4C1z85IJvKI1RWIf8Rr0SQJ_K9lY8AHoEYNtx3W9vG7fuSJGn3raTOHn0wsRvLENVi6csAPh6GMKB7inXAAHwAdIFAACNVzFhscRn-wIAAAAABFla)

We have written a dict comprehension that is generated using list comprehension, and when black formats it, it feels like it is treating it all as list comprehension. I would expect it to handle the list comprehension like as if it were a dict assignment. 

So, we are writing code that looks like: 
```python3
dict_list_comprehenstion = {
    m['email']: m for m in comprehension_data if m['kind'] == 'internal'
}
```

Which black formats to:
```python3
dict_list_comprehenstion = {
    m["email"]: m
    for m in comprehension_data
    if m["kind"] == "internal"
}
```

The black formatted version reduces the clarity of what is going on by putting the list comprehension lines on the same indentation as the key argument. List comprehension can already be easy to misread.

**Comment by JelleZijlstra** [comment]
It looks like there's no list comprehension involved in your example, only a dict comprehension.

Black will only split up the elements of the dict comprehension if it doesn't fit in one line otherwise. For example:
```
$ black --diff dcomp.py 
--- dcomp.py	2018-09-10 15:43:52.548892 +0000
+++ dcomp.py	2018-09-10 15:43:54.490608 +0000
@@ -1,2 +1,4 @@
-very_very_very_very_long_name_so_it_doesnt_fit_in_one_line = {x: y for x, y in d.items() if x}
+very_very_very_very_long_name_so_it_doesnt_fit_in_one_line = {
+    x: y for x, y in d.items() if x
+}
 
```
But if the condition is itself long Black will split it up:
```
$ black --diff dcomp.py 
--- dcomp.py	2018-09-10 15:45:16.958302 +0000
+++ dcomp.py	2018-09-10 15:45:19.145213 +0000
@@ -1,2 +1,6 @@
-very_very_very_very_long_name_so_it_doesnt_fit_in_one_line = {x: y for x, y in d.items() if very_long_condition_that_doesnt_fit_in_one_line_either(x)}
+very_very_very_very_long_name_so_it_doesnt_fit_in_one_line = {
+    x: y
+    for x, y in d.items()
+    if very_long_condition_that_doesnt_fit_in_one_line_either(x)
+}
```
That behavior all seems reasonable to me.

**Comment by ambv** [comment]
Putting elements of the comprehension on the same indentation level with "for" and "if" is a typical thing to do. If you see "for" inside a bracket pair, it tells you right away it's a comprehension. There is no other syntax that makes this keyword valid within a bracket pair. Since Black always dedents closing brackets on a separate line, it's visually obvious when you are inside a bracket pair.
