### ISSUE TITLE
[RFE] Order Set literals uniformly

### ISSUE THREAD

**Issue by behnam** [ambv/black#523]
*Black* version: black, version 18.6b4
(Didn't try master)

Would be great if we could uniformly order order `set` literals.

Basically, reordering:
```python
{
  Foo.B,
  Foo.A,
}
```
to
```python
{
  Foo.A,
  Foo.B,
}
```

From Python's perspective, the results are the same.

I guess there's only one difference in order of these items, and that's function side effects.

Arguably, such cases should be performed via `set()` and passing in an ordered list of items, and not via a literal.

Does that make sense?

**Comment by JelleZijlstra** [comment]
(Your example is a dictionary, not a set.)

This is risky in general because if multiple elements in a set or dict hash to the same value, the last one wins, so Black could not safely reorder arbitrary set/dict keys. If all the elements are basic types like ints, floats, or strings, that is not an issue though. 

Also, for dicts in Python 3.6+, insertion order is preserved, so if we reorder keys, we would be changing user-visible behavior. (For example, when you iterate over your first example, you are guaranteed to get B first, then A.)

**Comment by behnam** [comment]
Thanks, Jelle. Fixed the example.

Are the orders guaranteed to be preserved for `set`, as well? I mean, if it's an implementation detail, I'm happy for the literals changing during formatting.

**Comment by ambv** [comment]
@behnam, your suggestion is intriguing. As Jelle points out, it won't work for dictionaries because there might be duplicate keys with different values and the last one wins. Plus, insertion order is now preserved.

As far as I can tell, the danger for breaking set literals is very low. There are no "values" to be overwritten, just "keys". And hashes alone don't determine a collision: as long as the set members are not *equal*, they will be both preserved. But if they *are* equal and hash the same, then yes, the order in the literal determines which one will be accessible later... but at this point it probably doesn't matter.

However, I'm worried that people don't necessarily want alphabetically sorted literals, especially that for non-trivial members (e.g. members that are mathematical expressions, function calls, object instantiations, and so on) it might not be immediately obvious that what we're doing is sorting the members.

On the other hand, just special-casing ordering to sets that only contain number literals, strings, and singleton types (None, True, False) would be a nice addition.

Currently sets don't claim preservation of insertion order and their implementation does in fact rely on the order not being preserved. This could change in the future which would put us in an awkward situation had we implemented this.

**Comment by behnam** [comment]
Yeah, totally agree with the points mentioned here.

In the Rust world, `rustfmt` works very closely with the compiler and the language, and Rust being a strictly typed and compiled language, usually doesn't have any of these problems.

But, for cases that things can matter (like order), or it's just a matter of author's preference in some specific area/corner of the code base, there are linter attributes which gives back the full control to the author.

I believe Black is missing that control right now, and for some good reasons may not support such a thing at all. I think most of what I expect from Black fall in the category of not practical unless there's such a control, including dict/set auto-ordering, and imports auto-organization.

So, I close this RFE for now. I'll be happy to see it changing in the future.
