### ISSUE TITLE
Black never uses \

### ISSUE THREAD

**Issue by thomasahle** [ambv/black#531]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Darwin Kernel Version 17.2.0
Python version: 3.7.0
*Black* version: 18.6b4
Happens on master: yes

```
        train_x = list(swml_embedding.encode(examples)) \
                  + list(swml_embedding.encode(neutral))
```
is encoded by `black` as
```
        train_x = list(swml_embedding.encode(examples)) + list(
            swml_embedding.encode(neutral)
        )
```
This formatting makes it look like something different is happening in the second `list` than in the first one.

The problem happens because black only makes linebreaks inside parenthesis, and doesn't take advantage of the python backslash.

An alternative formatting would be
```
        train_x = (list(swml_embedding.encode(examples)) 
                   + list(swml_embedding.encode(neutral)))
```

**Comment by ambv** [comment]
Backslashes are the only piece of syntax in the Python grammar (besides multiline strings) that break significant indentation. I don't want them in Python code since they allow for formattings that confuse the human reader.

Note that introducing backslashes to Black would not fix your example issue. Black would still format as it is today because it doesn't understand the concept of symmetry. I agree with you that it would be nice if it formatted in a way that highlights symmetry. Sadly, this is currently well beyond the capabilities of the simple tool.

**Comment by thomasahle** [comment]
Hi Łukasz,

Would black be able to have a rule, such that expressions on the form `x = A + B + C` would be broken up around the operator (or weakest operator) when possible, rather than inside the expressions `A`, `B`, `C`?

Of course if not using backslash would then require adding a parenthesis around the expression, but I think adding and removing brackets is already something black does?

Thank you for a useful tool.

**Comment by ambv** [comment]
@thomasahle Black already does what you're asking for. See:

INPUT:
```py3
some_long_assignment_is_happening_here = VALUE(this_is_the_first_value) + VALUE(this_is_the_second_value) + VALUE(this_is_the_third_value)

```

OUTPUT:
```py3
some_long_assignment_is_happening_here = (
    VALUE(this_is_the_first_value)
    + VALUE(this_is_the_second_value)
    + VALUE(this_is_the_third_value)
)
```

It just doesn't do this if there is just a single operator. This is an optimization to avoid unnecessary optional parentheses all over the place.
