### ISSUE TITLE
Support config in setup.cfg

### ISSUE THREAD

**Issue by Natim** [ambv/black#688]
Today, the config of black is exclusively in pyproject.toml.

However some project relies on `setuptools.setup()` rather than [Flit](https://flit.readthedocs.io/en/latest/).

Would it be possible to also store the config in setup.cfg?
 Especially since the syntax would be the same?

```
[tool.black]
line-length = 99
include = \.pyi?$
exclude = \.git
          | \.hg
          | \.mypy_cache
          | \.tox
          | \.venv
          | _build
          | buck-out
          | build
          | dist
```

Note that other projects like zest.releaser, flake8, twine, wheel already support that.

**Comment by leplatrem** [comment]
I would be happy to contribute this, if it makes sense...

Indeed, in [our project](https://github.com/Kinto/kinto), we use the `setup.cfg` file to configure our package metadata, flake8 options, coverage, zest.releaser, etc.  Our `setup.py` is 2 lines long :wink: 

I read [this comment](https://github.com/ambv/black/issues/65#issuecomment-377768404) which made me doubt about what you'd think about this.

> note: `setup.cfg` [can read](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) the __version__ attribute instead of [parsing source files like it's done here](https://github.com/ambv/black/blob/1ec2470da7a040e0d7e3900c97305731826ab101/setup.py#L19-L25)

**Comment by JelleZijlstra** [comment]
Let's discuss this in #683.

**Comment by richardARPANET** [comment]
Support for this has been added to https://github.com/odwyersoftware/brunette :+1:

**Comment by JulianVolodia** [comment]
@richardARPANET maybe we should work on flake8 and other projects to support pyproject.toml?

**Comment by richardARPANET** [comment]
@JulianVolodia just because the black maintainer is stubborn? Pass

**Comment by JulianVolodia** [comment]
> @JulianVolodia just because the black maintainer is stubborn? Pass

sad... but true?

**Comment by mateusz-stint** [comment]
Main reason to support `setup.cfg` is because it would allow to have flake/pyling/isort/black/pytest/coverage settings in one neat file. Thanks to this root directory is clean and simple running of `flake8; isort; pytest --cov`.

I understand though - migrate to toml. But here flake also doesn't support it - https://gitlab.com/pycqa/flake8/-/issues/428.

**Comment by JulianVolodia** [comment]
@mateusz-stint but they wont even bc of that... I am thinking about automatic tracking of black mainstream for brunette

**Comment by jaklan** [comment]
@ambv I don't want to create a special issue for that, so I will just put my question here - the current adoption of `pyproject.toml` is much better than a few years ago, from my experience - almost all crucial Python dev tools already support it. The biggest blocker for a full migration to `pyproject.toml`-only setup is `flake8`. I just wonder have you ever discussed with guys to convince them to add support for `pyproject.toml`? I know they don't really bother about community requests because of their own opinions about TOML, but as the DIR maybe you would be able to change their attitude? Even the `tox`-like legacy support would be a big step forward here.

Imho the integrity of the dev ecosystem is pretty important for each language, and in case of Python it was quite problematic for years, but now we are in a state where we are really close to achieve that goal in terms of project configuration, next and next PEPs highlight the importance of `pyproject.toml`. It would be a real pity if these efforts would be anyhow impacted just because of one or two guys. Especially when `flake8` is a part of PyCQA, and it would be beneficial for all if PSF and PyCQA were in the same boat here.

Usually we can figure such issues just as a Python community, but unfortunately - that's not the case here 😕
