### ISSUE TITLE
Configure newline type

### ISSUE THREAD

**Issue by joaoe** [ambv/black#723]
Hi.

Iny my project we are using unix new lines "\n" but most poeple are working on windows and now and then a file creeps in with "\r\n". Seems black will use the newline found in the very first line of the file, so the inconsistency will remain across files.

I'd like if possible to specify in the pyproject.toml file the kind of newline to use, like
`newline={auto,windows,unix,osx}` or whatever keyword you'd find appropriate.

Thanks !

**Comment by zsol** [comment]
I think this is a reasonable thing to ask. Let me think out aloud: by nature of what it does, Black already has to deal with newlines. There's explicit logic in it to try and guess the user's intent and preserve the newline style.

Sometimes a user will accidentally (because their editor is misconfigured) feed a file to Black with the wrong line endings, and it won't do anything to stop the damage. It would be straightforward to have a flag or configuration option to turn off the guessing logic and force a certain line ending.

However, there are other tools that deal with this problem already (editor and version control configurations allow you to force certain line endings), so it's not very hard to solve outside of Black. On top of that, it would make it slightly more complicated to explain what Black does with newlines. It would also increase the number of configuration options for Black's users, which goes against the goal of the project.

Weighing all of this, I think it doesn't make sense to extend Black's scope to manipulating line endings.

**Comment by joaoe** [comment]
> Sometimes a user will accidentally (because their editor is misconfigured) feed a file to Black with the wrong line endings

That is exactly what is happening. Misconfigured editor and misconfigured git.
